name: continuous-integration

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache python dependencies
      id: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-${{ matrix.python-version }}-build-${{ hashFiles('**/setup.json') }}
        restore-keys:
          pip-${{ matrix.python-version }}-build

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .[pre-commit,tests]

    - name: Run pre-commit & linter
      run: |
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude ./samos/io/xsf.py
        # # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude ./samos/io/xsf.py

    - name: Test with pytest
      run: |
        cd tests
        pytest -sv .
